name: Datadog Broswer Tests
on:
  push:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  tests:
    name: Testing 
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install Datadog-ci
      run: npm install --save-dev @datadog/datadog-ci
    - name: Run Datadog Browser Tests
      run: datadog-ci synthetics run-tests --config datadog/prod.json
