name: Datadog Browser Tests
on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main
jobs:
  tests:
    name: Testing 
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Setup Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install Datadog-ci
      run: npm install -g @datadog/datadog-ci
    - name: Run Datadog Browser Tests
      env:
        ACTIONS_STEP_DEBUG: true
      run: ls -la; datadog-ci version; datadog-ci synthetics run-tests --config datadog/prod.json

