name: Datadog Browser Tests
on:
  push:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
jobs:
  tests:
    name: Testing 
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "🍏 This job's status is ${{ job.status }}."
    - name: Setup Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install Datadog-ci
      run: npm install -g @datadog/datadog-ci
    - name: Run Datadog Browser Tests
      env:
        DOCKER_BUILDKIT: 1
        ACTIONS_STEP_DEBUG: true
      run: ls -la; datadog-ci version; datadog-ci synthetics run-tests --config datadog/prod.json

