name: Datadog Browser Tests
on:
  push:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
jobs:
  tests:
    name: Testing 
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install Datadog-ci
      run: npm install -g @datadog/datadog-ci
    - name: Run Datadog Browser Tests
      env:
        DOCKER_BUILDKIT: 1
        ACTIONS_STEP_DEBUG: true
      run: ls; datadog-ci version; datadog-ci synthetics run-tests --config datadog/prod.json

