name: Selenium Tests
on:
  push:
    branches:
      - main
jobs:
  tests:
    name: Selenium Testing 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./selenium
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        sudo apt-get install -y chromium-chromedriver
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: Run Basic Selenium Test
      run: python run.py

