name: Selenium Tests
on:
  push:
    branches:
      - main
jobs:
  tests:
    name: Selenium Testing 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./selenium
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    # - run: which google-chrome
    # - name: Setup Chrome
    #   uses: browser-actions/setup-chrome@v1
    #   with:
    #     chrome-version: 133
    #     install-chromedriver: true
    #     install-dependencies: true
    - run: |
        google-chrome --version
        which google-chrome
        ls -l /usr/bin/google-chrome
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: Run Basic Selenium Test
      run: which google-chrome; python run.py

